version: "3.9"

services:
#  app:
#    build:
#      context: .
#      dockerfile: ./build/app/Dockerfile
#      args:
#        APP_NAME: app
#      target: development
#    container_name: go_dev_app
#    tty: true
#    stdin_open: true
#    volumes:
#      - ./:/app:cached
#    ports:
#      - 11234:1234

  developdb:
    image: ${DB_IMAGE}
    container_name: "rust_develop_db"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=${DEV_POSTGRES_USER}
      - POSTGRES_PASSWORD=${DEV_POSTGRES_PASSWORD}
      - POSTGRES_DB=${DEV_POSTGRES_DB}
      - POSTGRES_INITDB_ARGS=${DEV_POSTGRES_INITDB_ARGS}
      - PGDATA=${DEV_POSTGRES_PGDATA}
      - TZ=${DEV_POSTGRES_TIME_ZONE}
    volumes:
      - ./docker/database/postgresql/developdb/data:/var/lib/postgresql/data:cached
      - ./docker/database/postgresql/init:/docker-entrypoint-initdb.d
    ports:
      - "50432:5432"
    restart: on-failure

  testdb:
    image: ${DB_IMAGE}
    container_name: "rust_test_db"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=${TEST_POSTGRES_USER}
      - POSTGRES_PASSWORD=${TEST_POSTGRES_PASSWORD}
      - POSTGRES_DB=${TEST_POSTGRES_DB}
      - POSTGRES_INITDB_ARGS=${TEST_POSTGRES_INITDB_ARGS}
      - PGDATA=${TEST_POSTGRES_PGDATA}
      - TZ=${TEST_POSTGRES_TIME_ZONE}
    volumes:
      - ./docker/database/postgresql/testdb/data:/var/lib/postgresql/data:cached
      - ./docker/database/postgresql/init:/docker-entrypoint-initdb.d
    ports:
      - "50433:5432"
    restart: on-failure
