openapi: "3.0.2"
info:
paths:

components:
  schemas:
    SightCategory:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: id(PK)
          example: 1
        name:
          type: string
          description: 名前
          example: "観光施設"
      required:
        - id
        - name
