version: '3.9'

services:
  api-swagger-editor:
    container_name: "rust-api-swagger-editor-server"
    build:
      context: ./
      dockerfile: Dockerfile-editor
    ports:
      - "18188:8080"

  api-swagger-ui:
    container_name: "rust-api-swagger-ui-server"
    build:
      context: ./
      dockerfile: Dockerfile-ui
    ports:
      - "18189:8080"
