openapi: "3.0.2"
info:
paths:

components:
  schemas:
    GetSightCategoriesResponse:
      title: sight categories response
      type: object
      properties:
        categories:
          type: array
          items:
            $ref: '../sight_categories/sight_category.yaml#/components/schemas/SightCategory'
      required:
        - sight_categories
